name: image-build-deploy

on:
  push:
    branches:
      - 'master'

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: login to irohub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IROSTUB_DOCKERHUB_USER }}
          password: ${{ secrets.IROSTUB_DOCKERHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.IROSTUB_REPO }}/roxy-b:latest
