name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: login to irohub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IROHUB_URL }}
          username: ${{ secrets.IROHUB_USERNAME }}
          password: ${{ secrets.IROHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.IROHUB_URL }}/roxy-api-server:latest
  
#   reload:
#     needs: image-build-push
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#     -
#       name: pull and apply
#       uses: appleboy/ssh-action@v0.1.6
#       with: 
#         host: ${{ secrets.MASTER_HOST }}
#         username: ${{ secrets.MASTER_USERNAME }}
#         password: ${{ secrets.MASTER_PASSWORD }}
#         port: ${{ secrets.MASTER_PORT }}
#         script: cd ${{ secrets.ROXY_API_DEP_PATH }} && ${{ secrets.ROXY_API_DEP }}
